### PR TITLE
Trying to add python 3.12

### PR DESCRIPTION
**Pull request by oshadura**

### CODE REVIEW

**Comment by lgray** [comment]
python 3.13 is still missing a compatible numba version (and a few other things). It'll likely be a while before we can use it.

**Comment by oshadura** [comment]
thanks @lgray, other question how is crutial to keep `tflite-runtime` in the list of packages? Looks like it was not released for python 3.12 (?)

**Comment by lgray** [comment]
Ah, if tflite is just done we may need to add tensorflow (whatever is the smallest package of those available).

**Comment by lgray** [comment]
Though these we just for convenience since people were asking for TF and pytorch.

I think a better way to setup the images would be to have different images with different ML stacks in them (and then one with everything for weird setups). Triton can serve most people's needs, but it's harder to setup.

**Comment by oshadura** [comment]
Ah they renamed `tf-lite` as `litert` https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/ (https://github.com/google-ai-edge/litert)

**Pull request merged**
