### PR TITLE
Pin HTCondor for LPC

### PR DESCRIPTION
**Pull request by oshadura**
https://github.com/CoffeaTeam/lpcjobqueue/issues/38

### CODE REVIEW

**Comment by ikrommyd** [comment]
https://github.com/htcondor/htcondor/releases/tag/v24.2.2 claims that a bug was introduced in 24.2.1. Perhaps it's best to pin to 24.0.2?

**Comment by oshadura** [comment]
@ikrommyd, I was following suggestion of @nsmith- in Slack :) I can change to 24.0.2

**Comment by nsmith-** [comment]
From the release it seems to say 24.2.2 is not broken? Either way, 24.0.2 is fine I think

**Comment by ikrommyd** [comment]
> From the release it seems to say 24.2.2 is not broken? Either way, 24.0.2 is fine I think

Well it claims that 24.2.1 is withdrawn that's why I suggested the previous one.

**Pull request merged**
